server:
  host: localhost
  port: 8181
  readTimeout: 5
  writeTimeout: 5
database:
  host: 0.0.0.0
  user: warehouse
  password: warehouse
  dbname: warehouse
  port: 5432
  sslmode: disable
  TimeZone: Europe/Warsaw
cache:
  host: 0.0.0.0
  port: 6379
  poolSize: 20
  idleTimeout: 5
  readTimeout: 5
  writeTimeout: 5
  dialTimeout: 5